---
- name: redhat | Installing Pre-Reqs (Fedora)
  dnf:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
    - 'device-mapper-persistent-data'
    - 'libselinux-python'
    - 'lvm2'
    - 'yum-utils'
  become: true  
  when: ansible_distribution == "Fedora"

- name: redhat | Installing Pre-Reqs (!=Fedora)
  yum:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
    - 'device-mapper-persistent-data'
    - 'libselinux-python'
    - 'lvm2'
    - 'yum-utils'
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Uninstalling Old Docker Package (if exists)
  yum:
    name: "{{ packages }}"
    state: "absent"
  vars:
    packages:
    - 'container-selinux'
    - 'docker-common'
    - 'docker-engine'
    - 'docker-selinux'
    - 'docker'
  become: true

- name: redhat | adding Docker repo
  template:
    src: "etc/yum.repos.d/docker.repo.j2"
    dest: "/etc/yum.repos.d/docker.repo"
  become: true

- name: redhat | installing Docker
  yum:
    name: "docker-ce-{{ docker_version_redhat }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | installing Docker
  dnf:
    name: "docker-ce-{{ docker_version_redhat }}"
    state: present
  become: true
  when: ansible_distribution == "Fedora"
